//! The real-cargo integration test for the wasm guest build: the fixture
//! must compile for wasm32-unknown-unknown and the produced binary must
//! carry the `veryl.manifest` custom section and the component entry
//! points. This is the machine check that the guest crates stay
//! wasm-compatible.

#![cfg(not(target_family = "wasm"))]

use std::path::PathBuf;
use std::process::Command;

/// Names of the wasm exports generated by `veryl_component_export!`.
const GUEST_EXPORTS: &[&str] = &[
    "veryl_component_abi_version",
    "veryl_component_kind",
    "veryl_component_create",
    "veryl_component_destroy",
    "veryl_component_on_init",
    "veryl_component_on_reset",
    "veryl_component_on_clock",
    "veryl_component_on_finish",
    "veryl_component_call_method",
    "veryl_component_alloc",
    "veryl_component_free",
];

#[test]
fn wasm_guest_manifest_section_and_exports() {
    // Skip on environments without a cargo toolchain or the wasm32 std.
    if Command::new("cargo").arg("--version").output().is_err() {
        eprintln!("skipping: cargo not available");
        return;
    }
    let libdir = Command::new("rustc")
        .args([
            "--print",
            "target-libdir",
            "--target",
            "wasm32-unknown-unknown",
        ])
        .output();
    let has_wasm_std = libdir.is_ok_and(|out| {
        out.status.success() && PathBuf::from(String::from_utf8_lossy(&out.stdout).trim()).exists()
    });
    if !has_wasm_std {
        eprintln!("skipping: wasm32-unknown-unknown std not installed");
        return;
    }

    let fixture = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/test_component");
    // Shared across every wasm fixture build (also wasm_host.rs and the
    // wasm_transport e2e): the first build compiles, the rest are cargo
    // fingerprint hits, and `cargo clean` removes it.
    let target_dir =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/wasm-fixture");
    let output = Command::new("cargo")
        .args([
            "build",
            "--release",
            "--target",
            "wasm32-unknown-unknown",
            "--message-format=json",
        ])
        .current_dir(fixture)
        .env("CARGO_TARGET_DIR", &target_dir)
        .output()
        .expect("failed to run cargo");
    assert!(
        output.status.success(),
        "fixture wasm build failed:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let mut wasm_path: Option<PathBuf> = None;
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        let Ok(msg) = serde_json::from_str::<serde_json::Value>(line) else {
            continue;
        };
        if msg["reason"] != "compiler-artifact" {
            continue;
        }
        if let Some(files) = msg["filenames"].as_array() {
            for file in files {
                if let Some(path) = file.as_str()
                    && path.ends_with(".wasm")
                {
                    wasm_path = Some(PathBuf::from(path));
                }
            }
        }
    }
    let wasm_path = wasm_path.expect("fixture produced no .wasm");
    let wasm = std::fs::read(&wasm_path).unwrap();

    // The manifest is readable straight from the binary, without a runtime.
    let section = veryl_metadata::wasm_custom_section(&wasm, "veryl.manifest")
        .expect("veryl.manifest custom section missing");
    let json: serde_json::Value =
        serde_json::from_slice(section).expect("manifest section is not valid JSON");
    let counter = &json["types"]["fixture_counter"];
    assert_eq!(counter["kind"], "clocked");
    assert_eq!(counter["ports"][0]["name"], "out");
    assert_eq!(counter["ports"][0]["dir"], "output");

    // The component entry points must survive linking as wasm exports.
    let exports = export_names(&wasm);
    for name in GUEST_EXPORTS {
        assert!(
            exports.iter().any(|e| e == name),
            "missing wasm export `{name}` (exports: {exports:?})"
        );
    }
}

/// Names in the wasm export section (id 7).
fn export_names(wasm: &[u8]) -> Vec<String> {
    let mut rest = &wasm[8..];
    while !rest.is_empty() {
        let id = rest[0];
        let (size, r) = leb128_u32(&rest[1..]).unwrap();
        let (section, tail) = r.split_at(size as usize);
        rest = tail;
        if id != 7 {
            continue;
        }
        let (count, mut entries) = leb128_u32(section).unwrap();
        let mut names = Vec::new();
        for _ in 0..count {
            let (len, r) = leb128_u32(entries).unwrap();
            let (name, r) = r.split_at(len as usize);
            names.push(String::from_utf8(name.to_vec()).unwrap());
            // Skip the export kind byte and the index.
            let (_, r) = leb128_u32(&r[1..]).unwrap();
            entries = r;
        }
        return names;
    }
    vec![]
}

fn leb128_u32(bytes: &[u8]) -> Option<(u32, &[u8])> {
    let mut result: u64 = 0;
    for i in 0..5 {
        let b = *bytes.get(i)?;
        result |= u64::from(b & 0x7f) << (7 * i);
        if b & 0x80 == 0 {
            return Some((u32::try_from(result).ok()?, &bytes[i + 1..]));
        }
    }
    None
}
