//! Public API for user-defined Veryl verification components.
//!
//! A component is a Rust type implementing [`Component`], exported with
//! [`veryl_component_export!`]. The simulator drives it like an `always_ff`
//! process: hooks fire on clock edges, inputs observe pre-edge values and
//! outputs commit together with FFs (NBA semantics).

pub use anyhow::{Error, Result, anyhow, bail};

pub use veryl_component_sys as sys;

// Lets the code generated by the macros refer to `::veryl_component` even
// inside this crate (its own tests use the macros too).
extern crate self as veryl_component;

mod ctx;
pub mod testing;
mod value;

#[doc(hidden)]
pub mod export;

pub use ctx::{BuildCtx, ClockPort, CtxFile, InputPort, OutputPort, ResetPort, SimCtx, TraceVar};
pub use value::Value;
pub use veryl_component_macros::{Component, VerylInterface, component_impl};

/// Declared shape of a component, carried in the vtable for diagnostics.
/// `Unspecified` defers the inst/var form check to load-time inference.
#[derive(Clone, Copy, PartialEq, Eq, Debug, Default)]
#[repr(u32)]
pub enum ComponentKind {
    #[default]
    Unspecified = sys::VRL_KIND_UNSPECIFIED,
    /// Clocked component, instantiated with `inst`.
    Clocked = sys::VRL_KIND_CLOCKED,
    /// Method-only component, declared with `var`.
    MethodOnly = sys::VRL_KIND_METHOD_ONLY,
}

/// A typed set of ports bound to one modport of a Veryl interface,
/// implemented with `#[derive(VerylInterface)]`. A component embeds it as an
/// `#[interface]` field; the field name is the interface port name the
/// testbench connects (`axi: bus.monitor`), and each struct field binds to
/// the interface member of the same name.
///
/// The constants feed the embedding component's manifest, assembled by
/// const concatenation so that component's derive never needs to see this
/// type's definition.
pub trait VerylInterface: Sized {
    /// Interface path as the defining project sees it (e.g.
    /// `"$std::axi4_lite_if"`).
    const INTERFACE_PATH: &'static str;
    /// The modport these ports bind to.
    const MODPORT: &'static str;
    /// JSON array of the member declarations, e.g.
    /// `[{"member":"awvalid","dir":"input"}]`.
    const MEMBERS_JSON: &'static str;

    /// Resolves every member port under the given group name.
    fn resolve(ctx: &mut BuildCtx, group: &str) -> Result<Self>;
}

/// A user-defined verification component.
///
/// Thread-safety contract: the host serializes all calls into one instance,
/// but multiple instances of the same library may live on different threads
/// concurrently — any global/static state inside the component must be
/// thread-safe. `Sync` is not required because of the per-instance
/// serialization.
pub trait Component: Send + 'static {
    /// If left `Unspecified` the declaration form (inst/var) is only checked
    /// by load-time inference; stating it yields a direct diagnostic on
    /// mismatch.
    const KIND: ComponentKind = ComponentKind::Unspecified;

    /// JSON interface manifest, generated by `#[derive(Component)]` +
    /// `#[component_impl]` for analysis-time and load-time interface
    /// checks. A compile-time constant so exported libraries can serve the
    /// aggregate from the `veryl_component_manifest` entry point and embed
    /// it in the `veryl.manifest` wasm custom section. Hand-written
    /// implementations keep the default (no manifest, load-time checking
    /// only).
    const MANIFEST_JSON: Option<&'static str> = None;

    /// [`Self::MANIFEST_JSON`] as an owned string.
    fn manifest() -> Option<String>
    where
        Self: Sized,
    {
        Self::MANIFEST_JSON.map(str::to_string)
    }

    /// Called once per instance. Resolve ports and parameters here; a
    /// missing name or direction mismatch is a load-time error.
    fn new(ctx: &mut BuildCtx) -> Result<Self>
    where
        Self: Sized;

    /// Called once at time 0 before initial blocks run. Output writes here
    /// become direct initial values, visible from the first settle.
    fn on_init(&mut self, _ctx: &mut SimCtx) -> Result<()> {
        Ok(())
    }

    /// Called on reset assertion of a connected reset port.
    fn on_reset(&mut self, _ctx: &mut SimCtx) -> Result<()> {
        Ok(())
    }

    /// Called on each edge of a connected clock. Inputs read pre-edge
    /// values; outputs commit with FFs. The default errors so that a
    /// method-only component left connected to a clock fails at run time
    /// instead of silently doing nothing.
    fn on_clock(&mut self, _ctx: &mut SimCtx) -> Result<()> {
        bail!("on_clock not implemented")
    }

    /// Zero-time method call from the testbench (`inst.name(args)`).
    fn method(&mut self, name: &str, _args: &[Value], _ctx: &mut SimCtx) -> Result<Value> {
        bail!("unknown method: {name}")
    }

    /// Called when the test ends (normally or via `finish`/`fail`).
    /// A `fail` here still marks the test as failed.
    fn on_finish(&mut self, _ctx: &mut SimCtx) -> Result<()> {
        Ok(())
    }
}

/// Exports component types from a cdylib.
///
/// Invoked exactly once per crate, listing every exported type; the
/// generated entry points have fixed symbol names, so a second invocation
/// fails to compile.
///
/// Generates the `veryl_component_lookup` entry point resolving each name to
/// its vtable, plus a `VERYL_COMPONENT_TABLE` static usable for in-process
/// (dlopen-free) registration in tests.
///
/// When the crate is built for a wasm target the same table is exposed
/// through the `veryl_component_*` wasm entry points instead, and the
/// aggregated manifest is embedded as the `veryl.manifest` custom section
/// so it can be read from the binary without executing it.
///
/// ```ignore
/// veryl_component_export!("rv_iss" => RvIss, "monitor" => Monitor);
/// ```
#[macro_export]
macro_rules! veryl_component_export {
    ($($name:literal => $ty:ty),+ $(,)?) => {
        const _: () = {
            $(assert!(
                $crate::sys::is_valid_component_name($name),
                "component export names must be identifiers ([a-zA-Z_][0-9a-zA-Z_]*)",
            );)+
        };

        #[doc(hidden)]
        pub static VERYL_COMPONENT_TABLE: &[(&str, $crate::sys::VrlComponentVTable)] = &[
            $(($name, $crate::export::vtable::<$ty>())),+
        ];

        /// # Safety
        /// `name` must reference valid UTF-8 for the duration of the call.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn veryl_component_lookup(
            name: $crate::sys::VrlStr,
        ) -> *const $crate::sys::VrlComponentVTable {
            let name = unsafe { name.as_str() };
            for (n, vtable) in VERYL_COMPONENT_TABLE {
                if *n == name {
                    return vtable as *const _;
                }
            }
            ::std::ptr::null()
        }

        #[doc(hidden)]
        pub const VERYL_COMPONENT_MANIFEST_ENTRIES:
            &[(&str, ::core::option::Option<&str>)] = &[
            $(($name, <$ty as $crate::Component>::MANIFEST_JSON)),+
        ];

        #[doc(hidden)]
        pub const VERYL_COMPONENT_MANIFEST_LEN: usize =
            $crate::export::manifest_json_len(VERYL_COMPONENT_MANIFEST_ENTRIES);

        /// Aggregated JSON manifests of the exported types (only those
        /// declared with `#[derive(Component)]` + `#[component_impl]`),
        /// assembled at compile time.
        #[doc(hidden)]
        pub static VERYL_COMPONENT_MANIFEST_JSON: [u8; VERYL_COMPONENT_MANIFEST_LEN] =
            $crate::export::manifest_json_bytes(VERYL_COMPONENT_MANIFEST_ENTRIES);

        /// The host reads this once after loading the library.
        #[unsafe(no_mangle)]
        pub extern "C" fn veryl_component_manifest() -> $crate::sys::VrlStr {
            $crate::sys::VrlStr {
                ptr: VERYL_COMPONENT_MANIFEST_JSON.as_ptr(),
                len: VERYL_COMPONENT_MANIFEST_LEN,
            }
        }

        /// The same document as a wasm custom section, readable from the
        /// prebuilt binary without a wasm runtime.
        #[cfg(target_family = "wasm")]
        #[unsafe(link_section = "veryl.manifest")]
        #[used]
        #[doc(hidden)]
        pub static VERYL_COMPONENT_MANIFEST_SECTION: [u8; VERYL_COMPONENT_MANIFEST_LEN] =
            $crate::export::manifest_json_bytes(VERYL_COMPONENT_MANIFEST_ENTRIES);

        // wasm entry points mirroring the native vtable contract; the glue
        // lives in `veryl_component::export::wasm`.
        #[cfg(target_family = "wasm")]
        const _: () = {
            #[unsafe(no_mangle)]
            extern "C" fn veryl_component_abi_version() -> u32 {
                $crate::sys::VRL_COMPONENT_ABI_VERSION
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_kind(
                name_ptr: *const u8,
                name_len: usize,
            ) -> u32 {
                unsafe { $crate::export::wasm::kind(VERYL_COMPONENT_TABLE, name_ptr, name_len) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_create(
                name_ptr: *const u8,
                name_len: usize,
            ) -> u32 {
                unsafe { $crate::export::wasm::create(VERYL_COMPONENT_TABLE, name_ptr, name_len) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_destroy(handle: u32) {
                unsafe { $crate::export::wasm::destroy(handle) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_on_init(handle: u32) -> i32 {
                unsafe { $crate::export::wasm::on_init(handle) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_on_reset(handle: u32) -> i32 {
                unsafe { $crate::export::wasm::on_reset(handle) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_on_clock(handle: u32) -> i32 {
                unsafe { $crate::export::wasm::on_clock(handle) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_on_finish(handle: u32) -> i32 {
                unsafe { $crate::export::wasm::on_finish(handle) }
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_call_method(
                handle: u32,
                name_ptr: *const u8,
                name_len: usize,
                args: *const $crate::sys::VrlValue,
                nargs: usize,
                ret: *mut $crate::sys::VrlValue,
            ) -> i32 {
                unsafe {
                    $crate::export::wasm::call_method(handle, name_ptr, name_len, args, nargs, ret)
                }
            }

            #[unsafe(no_mangle)]
            extern "C" fn veryl_component_alloc(size: usize) -> *mut u8 {
                $crate::export::wasm::alloc(size)
            }

            #[unsafe(no_mangle)]
            unsafe extern "C" fn veryl_component_free(ptr: *mut u8, size: usize) {
                unsafe { $crate::export::wasm::free(ptr, size) }
            }
        };
    };
}
