publish: publish_x86_64_linux publish_x86_64_windows publish_x86_64_mac publish_aarch64_mac

publish_x86_64_linux:
	npm run deploy:linux-x64

publish_x86_64_windows:
	npm run deploy:win32-x64

publish_x86_64_mac:
	npm run deploy:darwin-x64

publish_aarch64_mac:
	npm run deploy:darwin-arm64
