name: Periodic

on:
  schedule:
  - cron: 0 0 * * SUN

# Avoid spurious curl HTTP/2 framing errors on crate download.
env:
  CARGO_HTTP_MULTIPLEXING: "false"
  CARGO_NET_RETRY: 10

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: 'true'
    - name: Run tests
      run: |
        cargo update
        cargo test
