name: Regression

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            rust: stable
            target: aarch64-unknown-linux-gnu
          - os: macOS-latest
            rust: stable
            target: aarch64-apple-darwin
          - os: windows-latest
            rust: stable
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            rust: stable
            target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
        with:
          shared-key: "${{ runner.os }}-test"
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Run tests
        run: cargo test --locked --target ${{ matrix.target }}

  gen_sv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
        with:
          shared-key: "${{ runner.os }}-gen_sv"
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Run gen_sv
        run: make gen_sv
      - name: Check gen_sv
        run: git diff --exit-code

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
        with:
          shared-key: "${{ runner.os }}-clippy"
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Run clippy
        run: cargo clippy -- -D warnings

  std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./.github/actions/setup-sccache
        with:
          rw_key_id: ${{ secrets.R2_CACHE_ACCESS_KEY_ID }}
          rw_secret: ${{ secrets.R2_CACHE_SECRET_ACCESS_KEY }}
          ro_key_id: ${{ secrets.R2_CACHE_RO_ACCESS_KEY_ID }}
          ro_secret: ${{ secrets.R2_CACHE_RO_SECRET_ACCESS_KEY }}
          s3_endpoint: ${{ secrets.R2_CACHE_S3_ENDPOINT }}
          bucket: ${{ secrets.R2_CACHE_BUCKET }}
      - name: Setup veryl
        run:  cargo build --profile release-verylup
      - name: Setup verilator
        uses: veryl-lang/setup-verilator@v2
      - name: Format check
        run: ../../../target/release-verylup/veryl fmt --check
        working-directory: crates/std/veryl
      - name: Build check
        run: ../../../target/release-verylup/veryl check
        working-directory: crates/std/veryl
      - name: Test
        run: ../../../target/release-verylup/veryl test --sim verilator
        working-directory: crates/std/veryl

  heliodor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: ./.github/actions/setup-sccache
        with:
          rw_key_id: ${{ secrets.R2_CACHE_ACCESS_KEY_ID }}
          rw_secret: ${{ secrets.R2_CACHE_SECRET_ACCESS_KEY }}
          ro_key_id: ${{ secrets.R2_CACHE_RO_ACCESS_KEY_ID }}
          ro_secret: ${{ secrets.R2_CACHE_RO_SECRET_ACCESS_KEY }}
          s3_endpoint: ${{ secrets.R2_CACHE_S3_ENDPOINT }}
          bucket: ${{ secrets.R2_CACHE_BUCKET }}
      - name: Setup veryl
        run: cargo build --profile release-verylup
      - name: Test
        run: ../../target/release-verylup/veryl test
        working-directory: testcases/heliodor

  cocotb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        continue-on-error: true
        with:
          shared-key: "${{ runner.os }}-release"
          save-if: ${{ github.ref == 'refs/heads/master' }}
      - name: Setup veryl
        run:  cargo build --profile release-verylup
      - name: Setup verilator
        uses: veryl-lang/setup-verilator@v2
      - name: Test cocotb 1.9.2
        run: |
          pip install "cocotb==1.9.2"
          target/release-verylup/veryl test --sim verilator testcases/veryl/67_cocotb.veryl
      - name: Test cocotb 2.0.0
        run: |
          pip install "cocotb==2.0.0"
          target/release-verylup/veryl test --sim verilator testcases/veryl/67_cocotb.veryl

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Build for wasm
        run: cargo check --target wasm32-unknown-unknown -p veryl-emitter -p veryl-formatter -p veryl-simulator

  highlightgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - uses: dtolnay/rust-toolchain@stable
      - name: Run highlightgen
        run: cargo run --bin highlightgen -- check
